# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      # postgres default username is: "postgres"
      POSTGRES_PASSWORD: postgres
    volumes:
      - data:/data

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8060:8080
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  data: {}

networks:
  default:
    name: postgres_network
